'use client';

import React, { useState } from 'react';
import { GlassCard } from '@/components/ui/GlassCard';
import { Badge } from '@/components/ui/Badge';
import {
  FileText,
  Download,
  Copy,
  Check,
  Plus,
  Trash2,
  ShieldCheck,
  Printer,
  Sparkles,
  Layers,
} from 'lucide-react';

interface Finding {
  id: string;
  title: string;
  severity: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'INFORMATIONAL';
  description: string;
  remediation: string;
}

export default function ReportGeneratorPage() {
  const [reportTitle, setReportTitle] = useState('Executive Cybersecurity Posture Audit');
  const [targetOrg, setTargetOrg] = useState('Acme Corp Infrastructure');
  const [assessorName, setAssessorName] = useState('Alex Morgan — Lead Security Analyst');
  const [summaryText, setSummaryText] = useState(
    'Comprehensive external defensive security assessment evaluating web security headers, public DNS architecture, email anti-spoofing policies (SPF/DMARC), and TLS certificates.'
  );

  const [findings, setFindings] = useState<Finding[]>([
    {
      id: 'f-1',
      title: 'Missing Strict-Transport-Security (HSTS) Policy',
      severity: 'HIGH',
      description: 'Web application responds over HTTPS but omits Strict-Transport-Security header, allowing potential SSL stripping attacks.',
      remediation: 'Add: Strict-Transport-Security: max-age=63072000; includeSubDomains; preload to web server reverse proxy.',
    },
    {
      id: 'f-2',
      title: 'DMARC Enforcement Policy Set to None (p=none)',
      severity: 'MEDIUM',
      description: 'The domain publishes a DMARC record but runs in monitoring mode (p=none), leaving domain name vulnerable to email impersonation.',
      remediation: 'Transition DMARC policy from p=none to p=quarantine, and subsequently p=reject.',
    },
  ]);

  const [copied, setCopied] = useState(false);

  const addFinding = () => {
    const newFinding: Finding = {
      id: `f-${Date.now()}`,
      title: 'New Discovered Security Finding',
      severity: 'MEDIUM',
      description: 'Describe the observed vulnerability or configuration weakness.',
      remediation: 'Specify remediation directives and verification steps.',
    };
    setFindings([...findings, newFinding]);
  };

  const removeFinding = (id: string) => {
    setFindings(findings.filter((f) => f.id !== id));
  };

  const updateFinding = (id: string, field: keyof Finding, val: string) => {
    setFindings(
      findings.map((f) => (f.id === id ? { ...f, [field]: val } : f))
    );
  };

  const generateMarkdownReport = () => {
    let md = `# ${reportTitle}\n\n`;
    md += `**Target:** ${targetOrg}  \n`;
    md += `**Assessor:** ${assessorName}  \n`;
    md += `**Date:** ${new Date().toLocaleDateString()}  \n`;
    md += `**Platform:** Generated by XTRACY Cybersecurity Intelligence Platform  \n\n`;
    md += `---\n\n`;
    md += `## 1. Executive Summary\n\n${summaryText}\n\n`;
    md += `## 2. Key Metrics & Findings Breakdown\n\n`;
    md += `Total Findings: **${findings.length}**  \n\n`;

    findings.forEach((f, idx) => {
      md += `### ${idx + 1}. [${f.severity}] ${f.title}\n\n`;
      md += `**Description:**  \n${f.description}\n\n`;
      md += `**Remediation Action:**  \n${f.remediation}\n\n`;
    });

    md += `---\n\n`;
    md += `*Report generated via XTRACY Cybersecurity Platform (https://xtracy.org)*\n`;
    return md;
  };

  const handleCopyMarkdown = () => {
    const md = generateMarkdownReport();
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="flex flex-col gap-8 animate-fadeIn max-w-5xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-gray-800 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-3xl font-black text-white flex items-center gap-2">
              <FileText className="w-8 h-8 text-brand-cyan" />
              Cybersecurity Report Generator
            </h1>
            <Badge type="productStatus" value="REPORT BUILDER" size="sm" />
          </div>
          <p className="text-xs text-gray-400 mt-1">
            Compile technical audit findings, severity metrics, and remediation directives into structured Markdown or printable executive reports.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopyMarkdown}
            className="px-4 py-2 rounded-xl bg-darkBg-panel hover:bg-gray-800 border border-gray-800 text-white font-bold text-xs flex items-center gap-1.5 transition-all"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied Markdown' : 'Copy Markdown'}</span>
          </button>
          <button
            onClick={handlePrint}
            className="px-4 py-2 rounded-xl bg-brand-blue hover:bg-brand-electric text-white font-bold text-xs flex items-center gap-1.5 shadow-glowBlue transition-all"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print Report</span>
          </button>
        </div>
      </div>

      {/* Report Metadata Configuration */}
      <GlassCard className="p-6 border-brand-blue/30 flex flex-col gap-4">
        <h2 className="text-xs font-bold text-white uppercase tracking-wider">
          Audit Report Metadata
        </h2>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
          <div className="flex flex-col gap-1">
            <label className="text-gray-400 font-semibold">Report Title:</label>
            <input
              type="text"
              value={reportTitle}
              onChange={(e) => setReportTitle(e.target.value)}
              className="p-2.5 rounded-xl bg-darkBg-panel border border-gray-800 text-white font-bold focus:border-brand-cyan"
            />
          </div>

          <div className="flex flex-col gap-1">
            <label className="text-gray-400 font-semibold">Target / Organization:</label>
            <input
              type="text"
              value={targetOrg}
              onChange={(e) => setTargetOrg(e.target.value)}
              className="p-2.5 rounded-xl bg-darkBg-panel border border-gray-800 text-white focus:border-brand-cyan"
            />
          </div>

          <div className="flex flex-col gap-1">
            <label className="text-gray-400 font-semibold">Assessor Name / Team:</label>
            <input
              type="text"
              value={assessorName}
              onChange={(e) => setAssessorName(e.target.value)}
              className="p-2.5 rounded-xl bg-darkBg-panel border border-gray-800 text-white focus:border-brand-cyan"
            />
          </div>
        </div>

        <div className="flex flex-col gap-1 text-xs">
          <label className="text-gray-400 font-semibold">Executive Summary:</label>
          <textarea
            value={summaryText}
            onChange={(e) => setSummaryText(e.target.value)}
            rows={3}
            className="p-3 rounded-xl bg-darkBg-panel border border-gray-800 text-white focus:border-brand-cyan"
          />
        </div>
      </GlassCard>

      {/* Discovered Findings List */}
      <GlassCard className="p-6 border-gray-800 flex flex-col gap-4">
        <div className="flex items-center justify-between border-b border-gray-800 pb-3">
          <h2 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
            <Layers className="w-4 h-4 text-brand-cyan" /> Audit Findings ({findings.length})
          </h2>
          <button
            onClick={addFinding}
            className="px-3.5 py-1.5 rounded-xl bg-brand-cyan text-black font-extrabold text-xs flex items-center gap-1 hover:scale-105 transition-all shadow-glowCyan"
          >
            <Plus className="w-3.5 h-3.5" />
            <span>Add Finding</span>
          </button>
        </div>

        <div className="flex flex-col gap-4">
          {findings.map((f, idx) => (
            <div
              key={f.id}
              className="p-4 rounded-xl bg-darkBg-panel border border-gray-800 flex flex-col gap-3 text-xs"
            >
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <div className="flex items-center gap-2 flex-1">
                  <span className="font-mono text-gray-500 font-bold">#{idx + 1}</span>
                  <input
                    type="text"
                    value={f.title}
                    onChange={(e) => updateFinding(f.id, 'title', e.target.value)}
                    placeholder="Finding Title..."
                    className="p-2 rounded-lg bg-darkBg border border-gray-800 text-white font-bold flex-1 focus:border-brand-cyan"
                  />
                </div>

                <div className="flex items-center gap-2 shrink-0">
                  <select
                    value={f.severity}
                    onChange={(e) => updateFinding(f.id, 'severity', e.target.value as any)}
                    className="p-2 rounded-lg bg-darkBg border border-gray-800 text-white font-bold"
                  >
                    <option value="CRITICAL">CRITICAL</option>
                    <option value="HIGH">HIGH</option>
                    <option value="MEDIUM">MEDIUM</option>
                    <option value="LOW">LOW</option>
                    <option value="INFORMATIONAL">INFORMATIONAL</option>
                  </select>

                  <button
                    onClick={() => removeFinding(f.id)}
                    className="p-2 rounded-lg bg-red-950 text-red-400 hover:bg-red-900"
                    title="Delete finding"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                <div className="flex flex-col gap-1">
                  <label className="text-[10px] text-gray-400 font-bold uppercase">Observed Issue / Description:</label>
                  <textarea
                    value={f.description}
                    onChange={(e) => updateFinding(f.id, 'description', e.target.value)}
                    rows={2}
                    className="p-2.5 rounded-lg bg-darkBg border border-gray-800 text-gray-300 text-[11px]"
                  />
                </div>

                <div className="flex flex-col gap-1">
                  <label className="text-[10px] text-brand-cyan font-bold uppercase">Remediation Action:</label>
                  <textarea
                    value={f.remediation}
                    onChange={(e) => updateFinding(f.id, 'remediation', e.target.value)}
                    rows={2}
                    className="p-2.5 rounded-lg bg-darkBg border border-gray-800 text-brand-cyan text-[11px]"
                  />
                </div>
              </div>
            </div>
          ))}
        </div>
      </GlassCard>
    </div>
  );
}
