import { IncidentPin } from '@/types';

export const MOCK_INCIDENT_PINS: IncidentPin[] = [
  {
    id: 'inc-01',
    title: 'Global Healthcare Cloud Provider Ransomware Disruption',
    region: 'North America',
    lat: 38.8951,
    lng: -77.0364,
    category: 'Ransomware',
    severity: 'CRITICAL',
    date: '2026-08-21',
    summary: 'Ransomware operation impacted administrative scheduling systems across regional medical centers.',
    isDemoData: true,
  },
  {
    id: 'inc-02',
    title: 'European Financial Portal OAuth Phishing Campaign',
    region: 'Europe',
    lat: 51.5074,
    lng: -0.1278,
    category: 'Phishing',
    severity: 'HIGH',
    date: '2026-08-19',
    summary: 'Targeted OAuth token harvesting campaign targeting online banking mobile applications.',
    isDemoData: true,
  },
  {
    id: 'inc-03',
    title: 'Asia-Pacific Telecommunications Zero-Day Exploit',
    region: 'Asia-Pacific',
    lat: 1.3521,
    lng: 103.8198,
    category: 'Vulnerabilities',
    severity: 'HIGH',
    date: '2026-08-17',
    summary: 'Critical vulnerability in edge routing firmware exploited prior to vendor patch release.',
    isDemoData: true,
  },
  {
    id: 'inc-04',
    title: 'E-Commerce Platform Customer Data Exposure',
    region: 'South America',
    lat: -23.5505,
    lng: -46.6333,
    category: 'Data Breach',
    severity: 'HIGH',
    date: '2026-08-14',
    summary: 'Misconfigured cloud storage bucket exposed non-sensitive transactional records.',
    isDemoData: true,
  },
  {
    id: 'inc-05',
    title: 'AI Voice Synthesis Extortion Syndicate',
    region: 'Middle East',
    lat: 25.2048,
    lng: 55.2708,
    category: 'Scam Campaign',
    severity: 'MEDIUM',
    date: '2026-08-12',
    summary: 'Organized scam network utilizing AI voice cloning for emergency distress scams.',
    isDemoData: true,
  },
];
