import { ThreatReport } from '@/types';

export const MOCK_THREAT_REPORTS: ThreatReport[] = [
  {
    id: 'TR-2026-081',
    title: 'Critical Android WebKit Arbitrary Code Execution Flaw',
    summary: 'A high-severity memory corruption vulnerability in Android WebKit permits remote code execution when viewing a crafted malicious website.',
    category: 'Critical Vulnerabilities',
    severity: 'CRITICAL',
    confidence: 'Officially Confirmed',
    affectedTags: ['Android', 'Chrome', 'Brave', 'Android 14', 'Android 13'],
    publishedAt: '2026-08-22',
    recommendedAction: 'Act Immediately',
    isDemoData: true,
    officialSource: 'CISA KEV Catalog & Android Security Bulletin',
    beginner: {
      simpleExplanation: 'A security flaw in Android phones allows bad websites to run hidden code on your phone just by opening a web page.',
      whyItMatters: 'If you use an Android phone and open a suspicious link in your browser, your device could be compromised without your knowledge.',
      immediateSteps: [
        'Open Google Play Store → tap profile → Manage apps & device → Update Google Chrome and Android System WebView immediately.',
        'Go to phone Settings → System → System Update and install any pending security patches.',
        'Avoid tapping links from unknown numbers or emails until your browser is updated.',
      ],
    },
    student: {
      overview: 'Use-after-free vulnerability in the WebKit/Blink engine allows heap corruption and out-of-bounds write access via crafted HTML/JavaScript.',
      concepts: ['Use-After-Free (UAF)', 'Heap Spraying', 'Sandbox Escape', 'Drive-by Download'],
      educationalNote: 'Browser rendering engines operate at high privileges. When a UAF occurs, attackers manipulate memory allocation to overwrite function pointers.',
      defensiveTakeaway: 'Immediate browser component updating remains the single most effective defense against WebKit memory corruption flaws.',
    },
    professional: {
      cve: 'CVE-2026-29104',
      cvssScore: 9.8,
      attackVector: 'Network / Remote (Unauthenticated)',
      affectedVersions: 'Android System WebView & Chrome prior to version 128.0.6613.114',
      mitreAttackId: 'T1189 - Drive-by Compromise',
      iocs: ['sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'],
      remediationSteps: [
        'Deploy Chrome / WebView v128.0.6613.114 across mobile device fleet.',
        'Enable Chrome Enhanced Safe Browsing policy on managed Android endpoints.',
        'Restrict installation of third-party browsers lacking automatic WebKit updates.',
      ],
      technicalReferences: ['https://source.android.com/security/bulletin', 'https://nvd.nist.gov/vuln/detail/CVE-2026-29104'],
    },
  },
  {
    id: 'TR-2026-079',
    title: 'Instagram & WhatsApp OAuth Token Hijacking Campaign Target Mobile Users',
    summary: 'Widespread social engineering scam uses fake verification portals to trick users into approving third-party OAuth logins, granting persistent account access.',
    category: 'Social Media Security',
    severity: 'HIGH',
    confidence: 'Verified',
    affectedTags: ['Instagram', 'WhatsApp', 'Meta', 'Android', 'iOS', 'iPhone'],
    publishedAt: '2026-08-20',
    recommendedAction: 'Secure Account',
    isDemoData: true,
    officialSource: 'XTRACY Threat Intelligence Alert',
    beginner: {
      simpleExplanation: 'Scammers are sending fake Instagram & WhatsApp messages claiming your account will be verified or deleted unless you log into a fake page.',
      whyItMatters: 'If you click "Approve" on the fake page, scammers steal control of your Instagram or WhatsApp without needing your password.',
      immediateSteps: [
        'Open Instagram → Settings → Security → Apps and Websites → Remove any unknown connected apps.',
        'Open WhatsApp → Settings → Linked Devices → Log out of all unrecognized web sessions.',
        'Enable Two-Factor Authentication using an Authenticator app (like Google or Microsoft Authenticator), not SMS.',
      ],
    },
    student: {
      overview: 'OAuth 2.0 authorization code injection combined with rogue web application consent screens bypasses standard password authentication.',
      concepts: ['OAuth 2.0 Authorization Flow', 'Consent Screen Phishing', 'Session Hijacking', 'Two-Factor Bypass'],
      educationalNote: 'Attackers create registered OAuth applications asking for read/write scope permissions. Users grant access believing it is an official Meta security tool.',
      defensiveTakeaway: 'Educate users to inspect OAuth authorization prompts and strictly limit third-party application permissions.',
    },
    professional: {
      cve: 'N/A (Social Engineering / Misconfiguration)',
      cvssScore: 8.1,
      attackVector: 'Web-based Social Engineering',
      affectedVersions: 'All Meta platform users interacting with rogue third-party OAuth scopes',
      mitreAttackId: 'T1528 - Steal Application Access Token',
      iocs: ['domain: verify-meta-badge-sec.xyz', 'domain: whatsapp-support-help-desk.work'],
      remediationSteps: [
        'Audit OAuth enterprise connected apps via Meta Business Manager.',
        'Enforce conditional access policy revoking long-lived refresh tokens upon location anomaly.',
        'Educate end users on identifying legitimate Meta domain URLs.',
      ],
      technicalReferences: ['https://help.instagram.com/security', 'https://www.cisa.gov/resources-tools/resources/phishing-guidance'],
    },
  },
  {
    id: 'TR-2026-075',
    title: 'Windows SmartScreen Security Bypass Exploited in Financial Phishing',
    summary: 'Active zero-day vulnerability in Microsoft Windows SmartScreen allows signed malicious shortcuts (.URL files) to bypass SmartScreen safety warnings.',
    category: 'Windows and Linux Security',
    severity: 'HIGH',
    confidence: 'Officially Confirmed',
    affectedTags: ['Windows', 'Windows 11', 'Windows 10', 'Outlook', 'Edge'],
    publishedAt: '2026-08-18',
    recommendedAction: 'Update',
    isDemoData: true,
    officialSource: 'Microsoft Security Response Center',
    beginner: {
      simpleExplanation: 'A flaw in Windows lets dangerous downloaded files run without showing the normal "Windows protected your PC" warning window.',
      whyItMatters: 'If you download or open files attached to suspicious emails on a Windows computer, Windows might not warn you before running them.',
      immediateSteps: [
        'Go to Windows Start → Settings → Windows Update → Check for Updates and install the latest cumulative patch.',
        'Do not open file attachments ending in .url, .lnk, or .iso received via email.',
        'Ensure Microsoft Defender Real-Time Protection is turned ON.',
      ],
    },
    student: {
      overview: 'Specially crafted internet shortcut files exploit a boundary check error in Windows Shell, failing to attach the Zone.Identifier Mark-of-the-Web (MOTW).',
      concepts: ['Mark of the Web (MOTW)', 'Zone.Identifier', 'SmartScreen Bypass', 'Shortcut File Execution'],
      educationalNote: 'MOTW tells Windows that a file originated from the internet zone. Without MOTW, SmartScreen filtering is bypassed completely.',
      defensiveTakeaway: 'Block incoming email attachments containing .url or compressed archives holding internet shortcuts at the email gateway layer.',
    },
    professional: {
      cve: 'CVE-2026-30112',
      cvssScore: 8.8,
      attackVector: 'Local / User Interaction (Email Attachment / Web Download)',
      affectedVersions: 'Windows 10, Windows 11, Windows Server 2022 prior to August 2026 Security Update',
      mitreAttackId: 'T1204.002 - User Execution: Malicious File',
      iocs: ['hash: 4f8a2190b2e3d8f1a1c4b9e2f5d7a8c3', 'filename: Invoice_Aug2026.url'],
      remediationSteps: [
        'Apply Microsoft KB5041580 security update across all domain workstation endpoints.',
        'Configure Attack Surface Reduction (ASR) rule: "Block executable files from running unless they meet a prevalence, age, or trusted list criterion".',
      ],
      technicalReferences: ['https://msrc.microsoft.com/update-guide/vulnerability/CVE-2026-30112'],
    },
  },
  {
    id: 'TR-2026-071',
    title: 'AI Deepfake Extortion & Impersonation Scams Target Women & Youth',
    summary: 'Surge in AI-generated voice cloning and image synthesis used in digital blackmail and fake emergency calls targeting family members.',
    category: 'Women\'s Digital Safety',
    severity: 'HIGH',
    confidence: 'Verified',
    affectedTags: ['Instagram', 'TikTok', 'WhatsApp', 'iPhone', 'Android'],
    publishedAt: '2026-08-15',
    recommendedAction: 'Act Immediately',
    isDemoData: true,
    officialSource: 'XTRACY Women\'s Safety & Privacy Research Center',
    beginner: {
      simpleExplanation: 'Cybercriminals are using AI tools to copy voices from public video posts or create fake pictures to blackmail or trick people for money.',
      whyItMatters: 'A scammer might call claiming to be a family member using a fake AI copy of their voice, or threaten you with fake generated images.',
      immediateSteps: [
        'Set up a secret "family code word" that only close family members know to verify emergency distress calls.',
        'Set your social media accounts (Instagram, TikTok) to Private to prevent strangers from downloading your photos or voice clips.',
        'If someone threatens you with synthetic/fake images, DO NOT PAY. Report immediately to official support and use the XTRACY Women\'s Safety Center guidance.',
      ],
    },
    student: {
      overview: 'Generative AI voice cloning requiring as little as 3 seconds of reference audio, combined with automated social media scraping for extortion campaigns.',
      concepts: ['Voice Cloning Synthesis', 'Generative Deepfakes', 'Digital Extortion', 'OSINT Harvesting'],
      educationalNote: 'Attacker automation harvests public video Reels/TikToks to train lightweight text-to-speech models, executing distress calls in near real-time.',
      defensiveTakeaway: 'Out-of-band verification (asking personal verification questions or secret passphrases) renders voice cloning ineffective.',
    },
    professional: {
      cve: 'N/A (AI Misuse & Social Engineering)',
      cvssScore: 7.9,
      attackVector: 'Telephony & Social Media Exploitation',
      affectedVersions: 'Public social media profiles with unencrypted voice/video content',
      mitreAttackId: 'T1598 - Phishing for Information (Impersonation)',
      iocs: ['tactics: AI voice cloning via VoIP spoofing', 'resource: StopNCII.org integration'],
      remediationSteps: [
        'Promote privacy settings education and social media footprint reduction.',
        'Provide immediate evidence preservation & escalation protocols for victims of non-consensual synthetic image abuse.',
      ],
      technicalReferences: ['https://stopncii.org', 'https://www.cybercivilrights.org'],
    },
  },
];
